[pytest]
addopts = -p no:cacheprovider
testpaths = tests
norecursedirs = .venv .pytest_tmp .pytest_cache pytest_tmp __pycache__
filterwarnings =
    ignore:.*setParseAction.*:DeprecationWarning
    ignore:.*copy keyword is deprecated.*:Warning
    ignore:.*set_(bad|over|under) function will be deprecated.*:PendingDeprecationWarning
    ignore:.*Co-variance matrix is underdetermined.*:UserWarning
